default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: hotwire_rails_development
  username: postgres
  password: admin
  host: localhost
  port: 5432

development:
  <<: *default
test:
  <<: *default
  database: hotwire_rails_test
production:
  <<: *default
  database: hotwire_rails_production
  username: hotwire_rails
  password: <%= ENV['HOTWIRE_RAILS_DATABASE_PASSWORD'] %>
